In [1]:
import pandas as pd
import numpy as np
from IPython.display import HTML
from io import BytesIO
import os

In [3]:
file="20191126 Cargas en Sell Out.xlsx"
xl= pd.ExcelFile(file)
sheetnames=xl.sheet_names
file=[pd.read_excel(file, sheet_names=s) for s in sheetnames]

cargas=pd.DataFrame(file[0])    
cargas

,nIdCarga,nIdRelProcesoFormato,nIdFormato,xDescripcion,X_CLIENTE,X_AGRUPADOR,X_PAIS,nIdPeriodo,D_FECHA,dInicio,dFin,xEstatus,nCargados,nProcesados,PROCESADOS,PIEZAS,PAQUETES,CORRUGADOS
0,2516,14,6,SellOut MX Portal (Benavides),BENAVIDES,NaN,MX,25,2019-10-01,2019-11-19 20:45:04.723,2019-11-19 20:48:27,TER,63536,33674,33674,1717711.00,109914.00,9647.345
1,2525,34,28,SellOut CAM (Feduro),AGENCIAS FEDURO (FEDURO),NaN,PN,24,2019-09-01,2019-11-21 18:00:45.177,2019-11-21 18:04:45,TER,29347,28803,28803,NaN,NaN,65257.138
2,2215,12,4,Sell Out Mayoristas,ANICETOS,ANICETOS,MX,23,2019-08-01,2019-10-10 15:53:08.173,2019-10-10 15:53:08,TER,83,83,83,7005506.00,384222.00,28096.000
3,2250,12,4,Sell Out Mayoristas,QUANTUM,QUANTUM,MX,23,2019-08-01,2019-10-10 17:01:58.250,2019-10-10 17:01:58,TER,60,60,60,11193852.00,406928.00,24509.000
4,2218,12,4,Sell Out Mayoristas,CAGSA,CAGSA,MX,23,2019-08-01,2019-10-10 15:57:30.260,2019-10-10 15:57:31,TER,100,79,79,3740923.48,181693.96,9927.220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2833,2420,58,51,SellOut MX Portales (Chedraui) Diario,CHEDRAUI,NaN,NaN,161,NaT,2019-10-31 21:15:58.027,2019-10-31 21:16:53,ERC,0,0,0,NaN,NaN,NaN
2834,2419,58,51,SellOut MX Portales (Chedraui) Diario,CHEDRAUI,NaN,NaN,161,NaT,2019-10-31 20:59:09.527,2019-10-31 21:05:10,ERC,0,0,0,NaN,NaN,NaN
2835,2421,58,51,SellOut MX Portales (Chedraui) Diario,CHEDRAUI,NaN,NaN,161,NaT,2019-10-31 21:17:15.367,2019-10-31 21:19:42,ERP,0,0,0,NaN,NaN,NaN
2836,2422,58,51,SellOut MX Portales (Chedraui) Diario,CHEDRAUI,NaN,NaN,161,NaT,2019-10-31 21:22:08.473,2019-10-31 21:23:55,ERP,0,0,0,NaN,NaN,NaN
2837,2423,58,51,SellOut MX Portales (Chedraui) Diario,CHEDRAUI,NaN,NaN,161,NaT,2019-11-01 16:54:37.207,2019-11-01 16:56:56,ERP,0,0,0,NaN,NaN,NaN

In [11]:
df= pd.crosstab(cargas.X_CLIENTE, [cargas.nIdPeriodo,cargas.D_FECHA], margins=True)
df.to_excel("fechas_titulo.xlsx", sheet_name="periodos" )
df

nIdPeriodo                                     4                      \
D_FECHA                      1900-01-01 00:00:00 2018-01-01 00:00:00
X_CLIENTE
19 HERMANOS                                    0                   1
ABAST_Z                                        0                   1
ABEJA                                          0                   1
AGENCIAS FEDURO (FEDURO)                       0                   0
ANICETOS                                       0                   1
...                                          ...                 ...
WALMART                                        0                   0
WALTER MARIN SEGURA (WAMASE)                   0                   0
Y GRIEGA                                       0                   1
ZORRO                                          0                   1
All                                            1                  56

nIdPeriodo                                     5                   6  \
D_FECHA                      2018-02-01 00:00:00 2018-03-01 00:00:00
X_CLIENTE
19 HERMANOS                                    1                   1
ABAST_Z                                        1                   1
ABEJA                                          1                   1
AGENCIAS FEDURO (FEDURO)                       0                   0
ANICETOS                                       1                   1
...                                          ...                 ...
WALMART                                        0                   0
WALTER MARIN SEGURA (WAMASE)                   0                   0
Y GRIEGA                                       1                   1
ZORRO                                          1                   1
All                                           59                  57

nIdPeriodo                                     7                   8  \
D_FECHA                      2018-04-01 00:00:00 2018-05-01 00:00:00
X_CLIENTE
19 HERMANOS                                    1                   1
ABAST_Z                                        1                   1
ABEJA                                          1                   1
AGENCIAS FEDURO (FEDURO)                       0                   0
ANICETOS                                       1                   1
...                                          ...                 ...
WALMART                                        0                   1
WALTER MARIN SEGURA (WAMASE)                   0                   0
Y GRIEGA                                       1                   1
ZORRO                                          1                   1
All                                           58                  59

nIdPeriodo                                     9                  10  \
D_FECHA                      2018-06-01 00:00:00 2018-07-01 00:00:00
X_CLIENTE
19 HERMANOS                                    1                   1
ABAST_Z                                        1                   1
ABEJA                                          1                   1
AGENCIAS FEDURO (FEDURO)                       0                   0
ANICETOS                                       1                   1
...                                          ...                 ...
WALMART                                        1                   1
WALTER MARIN SEGURA (WAMASE)                   0                   0
Y GRIEGA                                       1                   1
ZORRO                                          1                   1
All                                           60                  60

nIdPeriodo                                    11                  12  ...  \
D_FECHA                      2018-08-01 00:00:00 2018-09-01 00:00:00  ...
X_CLIENTE                                                             ...
19 HERMANOS                                    1                   1  ...
ABAST_Z                                        1                   1  ...
ABEJA                                          1                   1  ...
AGENCIAS FEDURO (FEDURO)                       0                   0  ...
ANICETOS                                       1                   1  ...
...                                          ...                 ...  ...
WALMART                                        1                   1  ...
WALTER MARIN SEGURA (WAMASE)                   0                   0  ...
Y GRIEGA                                       1                   1  ...
ZORRO                                          1                   1  ...
All                                           60                  60  ...

nIdPeriodo                                    17                  18  \
D_FECHA                      2019-02-01 00:00:00 2019-03-01 00:00:00
X_CLIENTE
19 HERMANOS                                    1                   1
ABAST_Z                                        1                   1
ABEJA                                          1                   1
AGENCIAS FEDURO (FEDURO)                       1                   0
ANICETOS                                       1                   1
...                                          ...                 ...
WALMART                                        1                   1
WALTER MARIN SEGURA (WAMASE)                   0                   0
Y GRIEGA                                       1                   1
ZORRO                                          1                   1
All                                           72                  66

nIdPeriodo                                    19                  20  \
D_FECHA                      2019-04-01 00:00:00 2019-05-01 00:00:00
X_CLIENTE
19 HERMANOS                                    1                   1
ABAST_Z                                        1                   0
ABEJA                                          1                   1
AGENCIAS FEDURO (FEDURO)                       0                   0
ANICETOS                                       1                   1
...                                          ...                 ...
WALMART                                        1                   1
WALTER MARIN SEGURA (WAMASE)                   0                   0
Y GRIEGA                                       1                   1
ZORRO                                          1                   1
All                                           65                  64

nIdPeriodo                                    21                  22  \
D_FECHA                      2019-06-01 00:00:00 2019-07-01 00:00:00
X_CLIENTE
19 HERMANOS                                    1                   1
ABAST_Z                                        1                   1
ABEJA                                          1                   1
AGENCIAS FEDURO (FEDURO)                       1                   1
ANICETOS                                       1                   1
...                                          ...                 ...
WALMART                                        1                   1
WALTER MARIN SEGURA (WAMASE)                   1                   1
Y GRIEGA                                       1                   1
ZORRO                                          1                   1
All                                           80                  74

nIdPeriodo                                    23                  24  \
D_FECHA                      2019-08-01 00:00:00 2019-09-01 00:00:00
X_CLIENTE
19 HERMANOS                                    1                   0
ABAST_Z                                        1                   0
ABEJA                                          1                   0
AGENCIAS FEDURO (FEDURO)                       1                   1
ANICETOS                                       1                   0
...                                          ...                 ...
WALMART                                        1                   0
WALTER MARIN SEGURA (WAMASE)                   1                   0
Y GRIEGA                                       1                   0
ZORRO                                          1                   0
All                                           89                   1

nIdPeriodo                                    25   All
D_FECHA                      2019-10-01 00:00:00
X_CLIENTE
19 HERMANOS                                    0    20
ABAST_Z                                        0    19
ABEJA                                          0    20
AGENCIAS FEDURO (FEDURO)                       0     5
ANICETOS                                       0    20
...                                          ...   ...
WALMART                                        0    16
WALTER MARIN SEGURA (WAMASE)                   0     3
Y GRIEGA                                       0    20
ZORRO                                          0    20
All                                            1  1286

[90 rows x 24 columns]

In [7]:
cargas[["D_FECHA","nIdPeriodo"]]

        D_FECHA  nIdPeriodo
0    2019-10-01          25
1    2019-09-01          24
2    2019-08-01          23
3    2019-08-01          23
4    2019-08-01          23
...         ...         ...
2833        NaT         161
2834        NaT         161
2835        NaT         161
2836        NaT         161
2837        NaT         161

[2838 rows x 2 columns]