In [1]:
import pandas as pd
import numpy as np
from IPython.display import HTML
import os

In [2]:
path = os.getcwd()
files = os.listdir(path)
files

['.ipynb_checkpoints',
 'CATALOGO SOLD TO - FORMATO (003) 020320.xlsx',
 'formato_tienda.xlsx',
 'REPORTE MONTHLY DIC ESSITY V3 (3).xlsm',
 'soriana2018',
 'soriana2018.rar',
 'soriana__mont.xlsx',
 'soriana__mont_2019.xlsx',
 'Untitled.ipynb',
 '~$formato_tienda.xlsx',
 '~$soriana__mont_2019.xlsx']

In [3]:
df = pd.read_excel('soriana__mont_2019.xlsx',skiprows=1,converters={'UPC': str})
df

,UPC,FORMATO,IMPORTE ENERO,PAQUETES ENERO,TRP ENERO,IMPORTE FEBRERO,PAQUETES FEBRERO,TRP FEBRERO,IMPORTE MARZO,PAQUETES MARZO,...,PAQUETES AGOSTO INV,TRP AGOSTO INV,PAQUETES SEPTIEMBRE INV,TRP SEPTIEMBRE INV,PAQUETES OCTUBRE INV,TRP OCTUBRE INV,PAQUETES NOVIEMBRE INV,TRP NOVIEMBRE INV,PAQUETES DICIEMBRE INV,TRP DICIEMBRE INV
0,7501019006081,S. EXP,53169.134159,1036,172.666667,31084.6518,491,81.833333,51647.6842,1091,...,428,71.333333,337,56.166667,245,40.833333,472,78.666667,462,77.000000
1,NaN,S. HIPER,240518.420715,4571,761.833333,209198.2209,4080,680.000000,223020.3141,4500,...,6203,1033.833333,4486,747.666667,2951,491.833333,3689,614.833333,2640,440.000000
2,NaN,S. MDO,107737.269512,2009,334.833333,86836.3620,1402,233.666667,136380.0764,2883,...,1808,301.333333,761,126.833333,546,91.000000,1317,219.500000,814,135.666667
3,NaN,S. MEGA,207683.563278,4141,690.166667,188198.0601,3984,664.000000,205104.5631,4267,...,0,0.000000,0,0.000000,0,0.000000,0,0.000000,0,0.000000
4,NaN,S. SUPER,40215.234402,749,124.833333,33269.0424,621,103.500000,35930.0206,696,...,169,28.166667,101,16.833333,138,23.000000,386,64.333333,197,32.833333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
978,NaN,S. MDO,0.000000,0,0.000000,0.0000,0,0.000000,0.0000,0,...,0,0.000000,0,0.000000,0,0.000000,0,0.000000,959,119.875000
979,NaN,S.CMR,0.000000,0,0.000000,0.0000,0,0.000000,0.0000,0,...,0,0.000000,0,0.000000,0,0.000000,0,0.000000,392,49.000000
980,7501019039751,S. HIPER,0.000000,0,0.000000,0.0000,0,0.000000,0.0000,0,...,0,0.000000,0,0.000000,0,0.000000,0,0.000000,36,3.000000
981,NaN,S. MDO,0.000000,0,0.000000,0.0000,0,0.000000,0.0000,0,...,0,0.000000,0,0.000000,0,0.000000,0,0.000000,2501,208.416667
982,NaN,S.CMR,0.000000,0,0.000000,0.0000,0,0.000000,0.0000,0,...,0,0.000000,0,0.000000,0,0.000000,0,0.000000,928,77.333333

In [4]:
upcFormat = []
for i in df["UPC"]:
    if pd.isnull(i):
        i=upcActual
    else:
        upcActual= i   
    upcFormat.append(i)
df['UPCT'] =pd.Series(upcFormat, index=df.index)

df

,UPC,FORMATO,IMPORTE ENERO,PAQUETES ENERO,TRP ENERO,IMPORTE FEBRERO,PAQUETES FEBRERO,TRP FEBRERO,IMPORTE MARZO,PAQUETES MARZO,...,TRP AGOSTO INV,PAQUETES SEPTIEMBRE INV,TRP SEPTIEMBRE INV,PAQUETES OCTUBRE INV,TRP OCTUBRE INV,PAQUETES NOVIEMBRE INV,TRP NOVIEMBRE INV,PAQUETES DICIEMBRE INV,TRP DICIEMBRE INV,UPCT
0,7501019006081,S. EXP,53169.134159,1036,172.666667,31084.6518,491,81.833333,51647.6842,1091,...,71.333333,337,56.166667,245,40.833333,472,78.666667,462,77.000000,7501019006081
1,NaN,S. HIPER,240518.420715,4571,761.833333,209198.2209,4080,680.000000,223020.3141,4500,...,1033.833333,4486,747.666667,2951,491.833333,3689,614.833333,2640,440.000000,7501019006081
2,NaN,S. MDO,107737.269512,2009,334.833333,86836.3620,1402,233.666667,136380.0764,2883,...,301.333333,761,126.833333,546,91.000000,1317,219.500000,814,135.666667,7501019006081
3,NaN,S. MEGA,207683.563278,4141,690.166667,188198.0601,3984,664.000000,205104.5631,4267,...,0.000000,0,0.000000,0,0.000000,0,0.000000,0,0.000000,7501019006081
4,NaN,S. SUPER,40215.234402,749,124.833333,33269.0424,621,103.500000,35930.0206,696,...,28.166667,101,16.833333,138,23.000000,386,64.333333,197,32.833333,7501019006081
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
978,NaN,S. MDO,0.000000,0,0.000000,0.0000,0,0.000000,0.0000,0,...,0.000000,0,0.000000,0,0.000000,0,0.000000,959,119.875000,7501019039669
979,NaN,S.CMR,0.000000,0,0.000000,0.0000,0,0.000000,0.0000,0,...,0.000000,0,0.000000,0,0.000000,0,0.000000,392,49.000000,7501019039669
980,7501019039751,S. HIPER,0.000000,0,0.000000,0.0000,0,0.000000,0.0000,0,...,0.000000,0,0.000000,0,0.000000,0,0.000000,36,3.000000,7501019039751
981,NaN,S. MDO,0.000000,0,0.000000,0.0000,0,0.000000,0.0000,0,...,0.000000,0,0.000000,0,0.000000,0,0.000000,2501,208.416667,7501019039751
982,NaN,S.CMR,0.000000,0,0.000000,0.0000,0,0.000000,0.0000,0,...,0.000000,0,0.000000,0,0.000000,0,0.000000,928,77.333333,7501019039751

In [5]:

#randrange(10)   
tiendaFormat = []
for i in df["FORMATO"]:
    if (i =="S. EXP"):tiendaFormat.append(355)
    if (i =="S. HIPER"):tiendaFormat.append(19)
    if (i =="S. MDO") : tiendaFormat.append(123)
    if (i =="S. SUPER"):tiendaFormat.append(213)
    if (i =="S. MEGA"):tiendaFormat.append(675)
    if (i =="S.CMR"):tiendaFormat.append(917)
    #if i =="S.EXP":

df['TIENDA'] =pd.Series(tiendaFormat, index=df.index)

df

,UPC,FORMATO,IMPORTE ENERO,PAQUETES ENERO,TRP ENERO,IMPORTE FEBRERO,PAQUETES FEBRERO,TRP FEBRERO,IMPORTE MARZO,PAQUETES MARZO,...,PAQUETES SEPTIEMBRE INV,TRP SEPTIEMBRE INV,PAQUETES OCTUBRE INV,TRP OCTUBRE INV,PAQUETES NOVIEMBRE INV,TRP NOVIEMBRE INV,PAQUETES DICIEMBRE INV,TRP DICIEMBRE INV,UPCT,TIENDA
0,7501019006081,S. EXP,53169.134159,1036,172.666667,31084.6518,491,81.833333,51647.6842,1091,...,337,56.166667,245,40.833333,472,78.666667,462,77.000000,7501019006081,355
1,NaN,S. HIPER,240518.420715,4571,761.833333,209198.2209,4080,680.000000,223020.3141,4500,...,4486,747.666667,2951,491.833333,3689,614.833333,2640,440.000000,7501019006081,19
2,NaN,S. MDO,107737.269512,2009,334.833333,86836.3620,1402,233.666667,136380.0764,2883,...,761,126.833333,546,91.000000,1317,219.500000,814,135.666667,7501019006081,123
3,NaN,S. MEGA,207683.563278,4141,690.166667,188198.0601,3984,664.000000,205104.5631,4267,...,0,0.000000,0,0.000000,0,0.000000,0,0.000000,7501019006081,675
4,NaN,S. SUPER,40215.234402,749,124.833333,33269.0424,621,103.500000,35930.0206,696,...,101,16.833333,138,23.000000,386,64.333333,197,32.833333,7501019006081,213
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
978,NaN,S. MDO,0.000000,0,0.000000,0.0000,0,0.000000,0.0000,0,...,0,0.000000,0,0.000000,0,0.000000,959,119.875000,7501019039669,123
979,NaN,S.CMR,0.000000,0,0.000000,0.0000,0,0.000000,0.0000,0,...,0,0.000000,0,0.000000,0,0.000000,392,49.000000,7501019039669,917
980,7501019039751,S. HIPER,0.000000,0,0.000000,0.0000,0,0.000000,0.0000,0,...,0,0.000000,0,0.000000,0,0.000000,36,3.000000,7501019039751,19
981,NaN,S. MDO,0.000000,0,0.000000,0.0000,0,0.000000,0.0000,0,...,0,0.000000,0,0.000000,0,0.000000,2501,208.416667,7501019039751,123
982,NaN,S.CMR,0.000000,0,0.000000,0.0000,0,0.000000,0.0000,0,...,0,0.000000,0,0.000000,0,0.000000,928,77.333333,7501019039751,917

In [6]:
meses = [
    "ENERO",
    "FEBRERO",
    "MARZO",
    "ABRIL",
    "MAYO",
    "JUNIO",
    "JULIO",
    "AGOSTO",
    "SEPTIEMBRE",
    "OCTUBRE",
    "NOVIEMBRE",
    "DICIEMBRE"    
]
contador = 1
for MES in meses:
    upcMes    = "UPCT"
    formatoMes= "FORMATO"
    importeMes= "IMPORTE "+MES
    trpMes    = "TRP "+MES
    paqMes    = "PAQUETES "+MES
    paqMesInv = "PAQUETES "+MES+" INV"
    tienda    = "TIENDA"
    
    dfMes= df[[tienda,upcMes, paqMes ,formatoMes,importeMes,trpMes,paqMesInv]]
    dfMes["mesNumero"]=contador
    dfMes["ano"]="2019"
    dfMes["compras_unidades"] = 0
    dfMes["importe_compra"] = 0
    #dfMes.astype({upcMes: 'int32'}).dtypes
    #dfMes[upcMes]
    #(dfMes[upcMes] - .0).round()
    #dfMes[upcMes] = dfMes[upcMes].astype(int)
    print(dfMes)    
    final=dfMes[["TIENDA","UPCT","ano","mesNumero",paqMes,"compras_unidades",paqMesInv,importeMes,"importe_compra",]]
    df1 = final[:440]
    df2 = final[440:]
    #print (ndata[:100])
    #df1, df2 = final[:10, :], final[10:, :]
    df1.to_csv("a"+str(contador)+"2019.txt", header=None, index=None, sep='!', mode='a')
    df2.to_csv("b"+str(contador)+"2019.txt", header=None, index=None, sep='!', mode='a')
    contador = contador + 1
    #print(final)
    #df=final

D:\c_anaconda\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\c_anaconda\lib\site-packages\ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\c_anaconda\lib\site-packages\ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
D:\c_anaconda\lib\site-packages\ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

     TIENDA           UPCT  PAQUETES ENERO   FORMATO  IMPORTE ENERO  \
0       355  7501019006081            1036    S. EXP   53169.134159
1        19  7501019006081            4571  S. HIPER  240518.420715
2       123  7501019006081            2009    S. MDO  107737.269512
3       675  7501019006081            4141   S. MEGA  207683.563278
4       213  7501019006081             749  S. SUPER   40215.234402
..      ...            ...             ...       ...            ...
978     123  7501019039669               0    S. MDO       0.000000
979     917  7501019039669               0     S.CMR       0.000000
980      19  7501019039751               0  S. HIPER       0.000000
981     123  7501019039751               0    S. MDO       0.000000
982     917  7501019039751               0     S.CMR       0.000000

      TRP ENERO  PAQUETES ENERO INV  mesNumero   ano  compras_unidades  \
0    172.666667                 720          1  2019                 0
1    761.833333                1807          1  2019                 0
2    334.833333                2324          1  2019                 0
3    690.166667                2811          1  2019                 0
4    124.833333                 281          1  2019                 0
..          ...                 ...        ...   ...               ...
978    0.000000                   0          1  2019                 0
979    0.000000                   0          1  2019                 0
980    0.000000                   0          1  2019                 0
981    0.000000                   0          1  2019                 0
982    0.000000                   0          1  2019                 0

     importe_compra
0                 0
1                 0
2                 0
3                 0
4                 0
..              ...
978               0
979               0
980               0
981               0
982               0

[983 rows x 11 columns]
     TIENDA           UPCT  PAQUETES FEBRERO   FORMATO  IMPORTE FEBRERO  \
0       355  7501019006081               491    S. EXP       31084.6518
1        19  7501019006081              4080  S. HIPER      209198.2209
2       123  7501019006081              1402    S. MDO       86836.3620
3       675  7501019006081              3984   S. MEGA      188198.0601
4       213  7501019006081               621  S. SUPER       33269.0424
..      ...            ...               ...       ...              ...
978     123  7501019039669                 0    S. MDO           0.0000
979     917  7501019039669                 0     S.CMR           0.0000
980      19  7501019039751                 0  S. HIPER           0.0000
981     123  7501019039751                 0    S. MDO           0.0000
982     917  7501019039751                 0     S.CMR           0.0000

     TRP FEBRERO  PAQUETES FEBRERO INV  mesNumero   ano  compras_unidades  \
0      81.833333                   367          2  2019                 0
1     680.000000                  1421          2  2019                 0
2     233.666667                  1234          2  2019                 0
3     664.000000                  2644          2  2019                 0
4     103.500000                   220          2  2019                 0
..           ...                   ...        ...   ...               ...
978     0.000000                     0          2  2019                 0
979     0.000000                     0          2  2019                 0
980     0.000000                     0          2  2019                 0
981     0.000000                     0          2  2019                 0
982     0.000000                     0          2  2019                 0

     importe_compra
0                 0
1                 0
2                 0
3                 0
4                 0
..              ...
978               0
979               0
980               0
981               0
982               0

[983 rows x 11 columns]
     TIENDA           UPCT  PAQUETES MARZO   FORMATO  IMPORTE MARZO  \
0       355  7501019006081            1091    S. EXP     51647.6842
1        19  7501019006081            4500  S. HIPER    223020.3141
2       123  7501019006081            2883    S. MDO    136380.0764
3       675  7501019006081            4267   S. MEGA    205104.5631
4       213  7501019006081             696  S. SUPER     35930.0206
..      ...            ...             ...       ...            ...
978     123  7501019039669               0    S. MDO         0.0000
979     917  7501019039669               0     S.CMR         0.0000
980      19  7501019039751               0  S. HIPER         0.0000
981     123  7501019039751               0    S. MDO         0.0000
982     917  7501019039751               0     S.CMR         0.0000

      TRP MARZO  PAQUETES MARZO INV  mesNumero   ano  compras_unidades  \
0    181.833333                 638          3  2019                 0
1    750.000000                3852          3  2019                 0
2    480.500000                1352          3  2019                 0
3    711.166667                3763          3  2019                 0
4    116.000000                 247          3  2019                 0
..          ...                 ...        ...   ...               ...
978    0.000000                   0          3  2019                 0
979    0.000000                   0          3  2019                 0
980    0.000000                   0          3  2019                 0
981    0.000000                   0          3  2019                 0
982    0.000000                   0          3  2019                 0

     importe_compra
0                 0
1                 0
2                 0
3                 0
4                 0
..              ...
978               0
979               0
980               0
981               0
982               0

[983 rows x 11 columns]
     TIENDA           UPCT  PAQUETES ABRIL   FORMATO  IMPORTE ABRIL  \
0       355  7501019006081             751    S. EXP     39024.6676
1        19  7501019006081            4662  S. HIPER    234240.1547
2       123  7501019006081            1868    S. MDO     96773.2970
3       675  7501019006081            3990   S. MEGA    192937.0926
4       213  7501019006081             632  S. SUPER     33533.3890
..      ...            ...             ...       ...            ...
978     123  7501019039669               0    S. MDO         0.0000
979     917  7501019039669               0     S.CMR         0.0000
980      19  7501019039751               0  S. HIPER         0.0000
981     123  7501019039751               0    S. MDO         0.0000
982     917  7501019039751               0     S.CMR         0.0000

      TRP ABRIL  PAQUETES ABRIL INV  mesNumero   ano  compras_unidades  \
0    125.166667                 338          4  2019                 0
1    777.000000                3407          4  2019                 0
2    311.333333                 972          4  2019                 0
3    665.000000                2975          4  2019                 0
4    105.333333                 201          4  2019                 0
..          ...                 ...        ...   ...               ...
978    0.000000                   0          4  2019                 0
979    0.000000                   0          4  2019                 0
980    0.000000                   0          4  2019                 0
981    0.000000                   0          4  2019                 0
982    0.000000                   0          4  2019                 0

     importe_compra
0                 0
1                 0
2                 0
3                 0
4                 0
..              ...
978               0
979               0
980               0
981               0
982               0

[983 rows x 11 columns]
     TIENDA           UPCT  PAQUETES MAYO   FORMATO   IMPORTE MAYO  \
0       355  7501019006081            560    S. EXP   35583.742172
1        19  7501019006081           4402  S. HIPER  242199.058666
2       123  7501019006081           1432    S. MDO   90599.669876
3       675  7501019006081              0   S. MEGA       0.000000
4       213  7501019006081            662  S. SUPER   36791.928436
..      ...            ...            ...       ...            ...
978     123  7501019039669              0    S. MDO       0.000000
979     917  7501019039669              0     S.CMR       0.000000
980      19  7501019039751              0  S. HIPER       0.000000
981     123  7501019039751              0    S. MDO       0.000000
982     917  7501019039751              0     S.CMR       0.000000

       TRP MAYO  PAQUETES MAYO INV  mesNumero   ano  compras_unidades  \
0     93.333333                638          5  2019                 0
1    733.666667               3852          5  2019                 0
2    238.666667               1352          5  2019                 0
3      0.000000               3763          5  2019                 0
4    110.333333                247          5  2019                 0
..          ...                ...        ...   ...               ...
978    0.000000                  0          5  2019                 0
979    0.000000                  0          5  2019                 0
980    0.000000                  0          5  2019                 0
981    0.000000                  0          5  2019                 0
982    0.000000                  0          5  2019                 0

     importe_compra
0                 0
1                 0
2                 0
3                 0
4                 0
..              ...
978               0
979               0
980               0
981               0
982               0

[983 rows x 11 columns]
     TIENDA           UPCT  PAQUETES JUNIO   FORMATO  IMPORTE JUNIO  \
0       355  7501019006081             849    S. EXP     48904.5381
1        19  7501019006081            4614  S. HIPER    250823.4377
2       123  7501019006081            2117    S. MDO    120679.9494
3       675  7501019006081            5310   S. MEGA    261760.9115
4       213  7501019006081             665  S. SUPER     37189.2262
..      ...            ...             ...       ...            ...
978     123  7501019039669               0    S. MDO         0.0000
979     917  7501019039669               0     S.CMR         0.0000
980      19  7501019039751               0  S. HIPER         0.0000
981     123  7501019039751               0    S. MDO         0.0000
982     917  7501019039751               0     S.CMR         0.0000

      TRP JUNIO  PAQUETES JUNIO INV  mesNumero   ano  compras_unidades  \
0    141.500000                1527          6  2019                 0
1    769.000000                3832          6  2019                 0
2    352.833333                3987          6  2019                 0
3    885.000000                6495          6  2019                 0
4    110.833333                 665          6  2019                 0
..          ...                 ...        ...   ...               ...
978    0.000000                   0          6  2019                 0
979    0.000000                   0          6  2019                 0
980    0.000000                   0          6  2019                 0
981    0.000000                   0          6  2019                 0
982    0.000000                   0          6  2019                 0

     importe_compra
0                 0
1                 0
2                 0
3                 0
4                 0
..              ...
978               0
979               0
980               0
981               0
982               0

[983 rows x 11 columns]
     TIENDA           UPCT  PAQUETES JULIO   FORMATO  IMPORTE JULIO  \
0       355  7501019006081            1454    S. EXP     73113.5741
1        19  7501019006081           14191  S. HIPER    552060.4733
2       123  7501019006081            6221    S. MDO    288522.2632
3       675  7501019006081               0   S. MEGA         0.0000
4       213  7501019006081            1337  S. SUPER     51465.9023
..      ...            ...             ...       ...            ...
978     123  7501019039669               0    S. MDO         0.0000
979     917  7501019039669               0     S.CMR         0.0000
980      19  7501019039751               0  S. HIPER         0.0000
981     123  7501019039751               0    S. MDO         0.0000
982     917  7501019039751               0     S.CMR         0.0000

       TRP JULIO  PAQUETES JULIO INV  mesNumero   ano  compras_unidades  \
0     242.333333                1498          7  2019                 0
1    2365.166667               14050          7  2019                 0
2    1036.833333                5257          7  2019                 0
3       0.000000                   0          7  2019                 0
4     222.833333                 354          7  2019                 0
..           ...                 ...        ...   ...               ...
978     0.000000                   0          7  2019                 0
979     0.000000                   0          7  2019                 0
980     0.000000                   0          7  2019                 0
981     0.000000                   0          7  2019                 0
982     0.000000                   0          7  2019                 0

     importe_compra
0                 0
1                 0
2                 0
3                 0
4                 0
..              ...
978               0
979               0
980               0
981               0
982               0

[983 rows x 11 columns]
     TIENDA           UPCT  PAQUETES AGOSTO   FORMATO  IMPORTE AGOSTO  \
0       355  7501019006081             1078    S. EXP      55088.2650
1        19  7501019006081             9158  S. HIPER     385245.0986
2       123  7501019006081             3811    S. MDO     180523.1814
3       675  7501019006081                0   S. MEGA          0.0000
4       213  7501019006081              936  S. SUPER      41749.4393
..      ...            ...              ...       ...             ...
978     123  7501019039669                0    S. MDO          0.0000
979     917  7501019039669                0     S.CMR          0.0000
980      19  7501019039751                0  S. HIPER          0.0000
981     123  7501019039751                0    S. MDO          0.0000
982     917  7501019039751                0     S.CMR          0.0000

      TRP AGOSTO  PAQUETES AGOSTO INV  mesNumero   ano  compras_unidades  \
0     179.666667                  428          8  2019                 0
1    1526.333333                 6203          8  2019                 0
2     635.166667                 1808          8  2019                 0
3       0.000000                    0          8  2019                 0
4     156.000000                  169          8  2019                 0
..           ...                  ...        ...   ...               ...
978     0.000000                    0          8  2019                 0
979     0.000000                    0          8  2019                 0
980     0.000000                    0          8  2019                 0
981     0.000000                    0          8  2019                 0
982     0.000000                    0          8  2019                 0

     importe_compra
0                 0
1                 0
2                 0
3                 0
4                 0
..              ...
978               0
979               0
980               0
981               0
982               0

[983 rows x 11 columns]

     TIENDA           UPCT  PAQUETES SEPTIEMBRE   FORMATO  IMPORTE SEPTIEMBRE  \
0       355  7501019006081                  683    S. EXP          36801.0621
1        19  7501019006081                 4219  S. HIPER         226820.6444
2       123  7501019006081                 1754    S. MDO          93845.6210
3       675  7501019006081                    0   S. MEGA              0.0000
4       213  7501019006081                  620  S. SUPER          33688.5181
..      ...            ...                  ...       ...                 ...
978     123  7501019039669                    0    S. MDO              0.0000
979     917  7501019039669                    0     S.CMR              0.0000
980      19  7501019039751                    0  S. HIPER              0.0000
981     123  7501019039751                    0    S. MDO              0.0000
982     917  7501019039751                    0     S.CMR              0.0000

     TRP SEPTIEMBRE  PAQUETES SEPTIEMBRE INV  mesNumero   ano  \
0        113.833333                      337          9  2019
1        703.166667                     4486          9  2019
2        292.333333                      761          9  2019
3          0.000000                        0          9  2019
4        103.333333                      101          9  2019
..              ...                      ...        ...   ...
978        0.000000                        0          9  2019
979        0.000000                        0          9  2019
980        0.000000                        0          9  2019
981        0.000000                        0          9  2019
982        0.000000                        0          9  2019

     compras_unidades  importe_compra
0                   0               0
1                   0               0
2                   0               0
3                   0               0
4                   0               0
..                ...             ...
978                 0               0
979                 0               0
980                 0               0
981                 0               0
982                 0               0

[983 rows x 11 columns]
     TIENDA           UPCT  PAQUETES OCTUBRE   FORMATO  IMPORTE OCTUBRE  \
0       355  7501019006081               704    S. EXP       38383.7539
1        19  7501019006081              4334  S. HIPER      220870.3129
2       123  7501019006081              1755    S. MDO       95018.9209
3       675  7501019006081                 0   S. MEGA           0.0000
4       213  7501019006081               636  S. SUPER       36006.6260
..      ...            ...               ...       ...              ...
978     123  7501019039669                 0    S. MDO           0.0000
979     917  7501019039669                 0     S.CMR           0.0000
980      19  7501019039751                 0  S. HIPER           0.0000
981     123  7501019039751                 0    S. MDO           0.0000
982     917  7501019039751                 0     S.CMR           0.0000

     TRP OCTUBRE  PAQUETES OCTUBRE INV  mesNumero   ano  compras_unidades  \
0     117.333333                   245         10  2019                 0
1     722.333333                  2951         10  2019                 0
2     292.500000                   546         10  2019                 0
3       0.000000                     0         10  2019                 0
4     106.000000                   138         10  2019                 0
..           ...                   ...        ...   ...               ...
978     0.000000                     0         10  2019                 0
979     0.000000                     0         10  2019                 0
980     0.000000                     0         10  2019                 0
981     0.000000                     0         10  2019                 0
982     0.000000                     0         10  2019                 0

     importe_compra
0                 0
1                 0
2                 0
3                 0
4                 0
..              ...
978               0
979               0
980               0
981               0
982               0

[983 rows x 11 columns]
     TIENDA           UPCT  PAQUETES NOVIEMBRE   FORMATO  IMPORTE NOVIEMBRE  \
0       355  7501019006081                 831    S. EXP         42007.4684
1        19  7501019006081                4676  S. HIPER        228192.9226
2       123  7501019006081                2255    S. MDO        112510.4819
3       675  7501019006081                   0   S. MEGA             0.0000
4       213  7501019006081                 679  S. SUPER         36877.8100
..      ...            ...                 ...       ...                ...
978     123  7501019039669                   0    S. MDO             0.0000
979     917  7501019039669                   0     S.CMR             0.0000
980      19  7501019039751                   0  S. HIPER             0.0000
981     123  7501019039751                   0    S. MDO             0.0000
982     917  7501019039751                   0     S.CMR             0.0000

     TRP NOVIEMBRE  PAQUETES NOVIEMBRE INV  mesNumero   ano  compras_unidades  \
0       138.500000                     472         11  2019                 0
1       779.333333                    3689         11  2019                 0
2       375.833333                    1317         11  2019                 0
3         0.000000                       0         11  2019                 0
4       113.166667                     386         11  2019                 0
..             ...                     ...        ...   ...               ...
978       0.000000                       0         11  2019                 0
979       0.000000                       0         11  2019                 0
980       0.000000                       0         11  2019                 0
981       0.000000                       0         11  2019                 0
982       0.000000                       0         11  2019                 0

     importe_compra
0                 0
1                 0
2                 0
3                 0
4                 0
..              ...
978               0
979               0
980               0
981               0
982               0

[983 rows x 11 columns]
     TIENDA           UPCT  PAQUETES DICIEMBRE   FORMATO  IMPORTE DICIEMBRE  \
0       355  7501019006081                 916    S. EXP         50001.4706
1        19  7501019006081                5039  S. HIPER        250352.5640
2       123  7501019006081                2601    S. MDO        135869.9402
3       675  7501019006081                   0   S. MEGA             0.0000
4       213  7501019006081                 691  S. SUPER         38293.4937
..      ...            ...                 ...       ...                ...
978     123  7501019039669                2249    S. MDO        171892.4858
979     917  7501019039669                 903     S.CMR         69470.7271
980      19  7501019039751                   0  S. HIPER             0.0000
981     123  7501019039751                 215    S. MDO          7947.5957
982     917  7501019039751                  80     S.CMR          2958.6210

     TRP DICIEMBRE  PAQUETES DICIEMBRE INV  mesNumero   ano  compras_unidades  \
0       152.666667                     462         12  2019                 0
1       839.833333                    2640         12  2019                 0
2       433.500000                     814         12  2019                 0
3         0.000000                       0         12  2019                 0
4       115.166667                     197         12  2019                 0
..             ...                     ...        ...   ...               ...
978     281.125000                     959         12  2019                 0
979     112.875000                     392         12  2019                 0
980       0.000000                      36         12  2019                 0
981      17.916667                    2501         12  2019                 0
982       6.666667                     928         12  2019                 0

     importe_compra
0                 0
1                 0
2                 0
3                 0
4                 0
..              ...
978               0
979               0
980               0
981               0
982               0

[983 rows x 11 columns]